# Generated by Django 5.2.13 on 2026-10-02 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('sitios', '0002_seed_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos', to='sitios.sitio'),
        ),
        migrations.AddConstraint(
            model_name='concepto',
            constraint=models.UniqueConstraint(fields=('sitio', 'nombre'), name='uq_sitio_concepto_nombre'),
        ),
    ]
