# Generated by Django 5.2.13 on 2026-10-09 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_concepto_activo_alter_concepto_sitio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecioConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='catalogo.concepto')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_precio_conceptos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_modificacion', '-id'],
            },
        ),
    ]
