# Generated by Django 5.2.13 on 2026-10-02 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='identificacion',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='stockelemento',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='proveedores.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='stockelemento',
            constraint=models.UniqueConstraint(fields=('proveedor', 'nombre_elemento'), name='uq_proveedor_elemento'),
        ),
    ]
