# Generated by Django 5.2.13 on 2026-10-02 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('sitios', '0002_seed_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('cotizado', 'Cotizado'), ('bloqueado', 'Bloqueado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], db_index=True, default='cotizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_evento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='sitios.sitio'),
        ),
    ]
