# Generated by Django 5.2.13 on 2026-10-11 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copiar_impuesto_del_concepto(apps, schema_editor):
    """Los items creados antes de esta migración toman el impuesto actual de su concepto."""
    CotizacionItem = apps.get_model("cotizaciones", "CotizacionItem")
    Concepto = apps.get_model("catalogo", "Concepto")
    CotizacionItem.objects.update(
        impuesto_pct=models.Subquery(
            Concepto.objects.filter(pk=models.OuterRef("concepto_id")).values("impuesto_pct")[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_alter_cotizacion_estado_and_more'),
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='garantia_registrada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='garantia_registrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garantias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='impuesto_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.RunPython(copiar_impuesto_del_concepto, migrations.RunPython.noop),
    ]
