# Generated by Django 5.2.13 on 2026-10-02 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0003_salon_foto_url'),
        ('sitios', '0002_seed_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='salon',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salones', to='sitios.sitio'),
        ),
        migrations.AlterField(
            model_name='salonmontaje',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='montajes', to='salones.salon'),
        ),
        migrations.AddConstraint(
            model_name='salon',
            constraint=models.UniqueConstraint(fields=('sitio', 'nombre'), name='uq_sitio_salon_nombre'),
        ),
    ]
